// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TranslateToPseudoEnglish
{
    internal sealed partial class Vsix
    {
        public const string Id = "TranslateToPseudoEnglish.e7f98b18-43e6-4740-8c6a-4fb4d63b27ef";
        public const string Name = "TranslateToPseudoEnglish";
        public const string Description = @"Instantly translate English to Pseudo-English of any selected text.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Balaji Mannar Kala";
        public const string Tags = "";
    }
}
