// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TranslateToPseudoEnglish
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TranslateToPseudoEnglishString = "62f8c62f-75b6-48d9-92a8-b5c85048ea97";
        public static Guid TranslateToPseudoEnglish = new Guid(TranslateToPseudoEnglishString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ArcoMenuGroup = 0x0001;
        public const int TranslateToPseudoEnglishCommand = 0x0100;
    }
}